// ---------------------------------------------------------------------------
// Datos maestros tomados de las hojas DATOS / Hoja2 de los libros originales
// ---------------------------------------------------------------------------
const RESPONSABLES = [
  "Diego Morales",
  "José Perez",
  "Vladimir Castro",
  "Evelyn Ordoñez",
  "Minor Mesén"
];

const AREAS_BPM = ["Empaque", "Pilado", "Frijoles", "Secado"];
const AREAS_DAC = ["Empaque", "Pilado", "Frijoles", "Secado", "Laboratorio"];
const AREAS_EPP = ["Pilado", "Secado", "Mantenimiento", "Frijoles", "Empaque"];

const DIAS_SEMANA = [
  { key: "L", label: "Lunes" },
  { key: "M", label: "Martes" },
  { key: "K", label: "Miércoles" },
  { key: "J", label: "Jueves" },
  { key: "V", label: "Viernes" },
  { key: "S", label: "Sábado" }
];

// Productos / presentaciones del R-PLP-001 (hoja DATOS)
const PRODUCTOS = [
  { codigo: "1",   nombre: "Banda",                 calidad: "N/A" },
  { codigo: "2",   nombre: "INTERGLO 80%",          calidad: "80%" },
  { codigo: "3",   nombre: "INTERGLO 90%",          calidad: "90%" },
  { codigo: "4",   nombre: "INTERGLO 95%",          calidad: "95%" },
  { codigo: "5",   nombre: "QUEBRADO",              calidad: "N/A" },
  { codigo: "23",  nombre: "DP 95% 23 KG",          calidad: "95%" },
  { codigo: "70",  nombre: "LB 99% 46 KG",          calidad: "99%" },
  { codigo: "71",  nombre: "LB 99% 1.8 KG",         calidad: "99%" },
  { codigo: "72",  nombre: "LB 99% 1.8 KG",         calidad: "99%" },
  { codigo: "73",  nombre: "LB 99% 4 KG",           calidad: "99%" },
  { codigo: "76",  nombre: "LB 99% 1 KG",           calidad: "99%" },
  { codigo: "77",  nombre: "LB 99% 23 KG",          calidad: "99%" },
  { codigo: "78",  nombre: "LB 99% 6 KG",           calidad: "99%" },
  { codigo: "101", nombre: "LB 95% 2 KG",           calidad: "95%" },
  { codigo: "102", nombre: "LB 95% 6 KG",           calidad: "95%" },
  { codigo: "103", nombre: "LB 95% 46 KG",          calidad: "95%" },
  { codigo: "104", nombre: "LB 90% 2 KG",           calidad: "90%" },
  { codigo: "106", nombre: "LB 80% 1.8 KG",         calidad: "80%" },
  { codigo: "107", nombre: "LB 80% 2 KG",           calidad: "80%" },
  { codigo: "109", nombre: "LB 80% 10 KG",          calidad: "80%" },
  { codigo: "110", nombre: "LB 80% 23 KG",          calidad: "80%" },
  { codigo: "111", nombre: "LB 80% 46 KG",          calidad: "80%" },
  { codigo: "114", nombre: "LB 95% 1.8 KG",         calidad: "95%" },
  { codigo: "118", nombre: "LB 95% 23 KG",          calidad: "95%" },
  { codigo: "122", nombre: "LB 90% 46 KG",          calidad: "90%" },
  { codigo: "125", nombre: "LB 90% 23 KG",          calidad: "90%" },
  { codigo: "130", nombre: "LB 90% 5 KG",           calidad: "90%" },
  { codigo: "134", nombre: "CNP 95% 2 KG",          calidad: "95%" },
  { codigo: "150", nombre: "DP 91% 1.8 KG",         calidad: "91%" },
  { codigo: "154", nombre: "LB 90% 1.8 KG",         calidad: "90%" },
  { codigo: "156", nombre: "LB 90% 8 KG",           calidad: "90%" },
  { codigo: "175", nombre: "DP 80% 1.8 KG",         calidad: "80%" },
  { codigo: "176", nombre: "DP 80% 10 KG",          calidad: "80%" },
  { codigo: "180", nombre: "DP 80% 46 KG",          calidad: "80%" },
  { codigo: "183", nombre: "DP 90% 1.8 KG",         calidad: "90%" },
  { codigo: "184", nombre: "DP 95% 1.8 KG",         calidad: "95%" },
  { codigo: "186", nombre: "DP 95% 7 KG",           calidad: "95%" },
  { codigo: "192", nombre: "DP 95% 5 KG",           calidad: "95%" },
  { codigo: "199", nombre: "DP 95% 46 KG",          calidad: "95%" },
  { codigo: "200", nombre: "DP 90% 8 KG",           calidad: "90%" },
  { codigo: "202", nombre: "DP 99% 1.8 KG",         calidad: "99%" },
  { codigo: "205", nombre: "DP 99% 4 KG",           calidad: "99%" },
  { codigo: "207", nombre: "DP 98% 46 KG",          calidad: "98%" },
  { codigo: "208", nombre: "DP 90% 46 KG",          calidad: "90%" },
  { codigo: "209", nombre: "DP 90% 1.5 KG",         calidad: "90%" },
  { codigo: "211", nombre: "CAÑERO 80% 1.8 KG",     calidad: "80%" },
  { codigo: "216", nombre: "DP 99% 7 KG",           calidad: "99%" },
  { codigo: "218", nombre: "CAÑERO 90% 1.5 KG",     calidad: "90%" },
  { codigo: "220", nombre: "CAÑERO 90% 5 KG",       calidad: "90%" },
  { codigo: "407", nombre: "LB FIT 99% 1.8 KG",     calidad: "99%" },
  { codigo: "411", nombre: "LB FIT 99% 1 KG",       calidad: "99%" },
  { codigo: "412", nombre: "LB FIT 99% 1.8 KG",     calidad: "99%" },
  { codigo: "511", nombre: "VILMA 90% 1.8 KG",      calidad: "90%" },
  { codigo: "512", nombre: "VILMA 99% 1.8 KG",      calidad: "99%" },
  { codigo: "513", nombre: "VILMA 80% 1.8 KG",      calidad: "80%" },
  { codigo: "515", nombre: "ANGEL 90% 1.8 KG",      calidad: "90%" },
  { codigo: "517", nombre: "ANGEL 99% 1.8 KG",      calidad: "99%" },
  { codigo: "518", nombre: "MTL 80% 1.8 KG",        calidad: "80%" },
  { codigo: "519", nombre: "MTL 91% 1.8 KG",        calidad: "91%" },
  { codigo: "520", nombre: "MTL 99% 1.8 KG",        calidad: "99%" },
  { codigo: "529", nombre: "ML 95% 1.8 KG",         calidad: "95%" },
  { codigo: "530", nombre: "ML 95% 5 KG",           calidad: "95%" },
  { codigo: "531", nombre: "ML 95% 3 KG",           calidad: "95%" },
  { codigo: "532", nombre: "CKP 80% 1.8 KG",        calidad: "80%" },
  { codigo: "534", nombre: "CKP 90% 1.8 KG",        calidad: "90%" },
  { codigo: "535", nombre: "CKP 99% 1.8 KG",        calidad: "99%" },
  { codigo: "536", nombre: "BM 90% 1.8 KG",         calidad: "90%" },
  { codigo: "537", nombre: "BM 95% 1.8 KG",         calidad: "95%" },
  { codigo: "538", nombre: "BM 99% 1.8 KG",         calidad: "99%" },
  { codigo: "539", nombre: "BM 99% 3.8 KG",         calidad: "99%" },
  { codigo: "",    nombre: "ANGEL 80% 1.8 KG",      calidad: "80%" },
  { codigo: "",    nombre: "DP 99% 1.5 KG",         calidad: "99%" }
];

// Mapa código de producto → calidad (número), derivado del catálogo de
// productos. Ej. 71 → 99. Se usa para autocompletar la calidad en el ETP.
const CODIGO_CALIDAD = {};
PRODUCTOS.forEach(function (p) {
  const m = String(p.calidad || "").match(/(\d+)\s*%/);
  if (p.codigo && m) CODIGO_CALIDAD[String(p.codigo).trim()] = m[1];
});
// Lista de códigos disponibles (para el selector del ETP).
const CODIGOS_PRODUCTO = Object.keys(CODIGO_CALIDAD);

// Los usuarios iniciales se crean en el backend (server/db.js) a partir de las
// variables de entorno SEED_ADMIN_PASSWORD y SEED_OPERATOR_PASSWORD la primera
// vez que arranca el servicio. El frontend ya no conoce credenciales.

// ---------------------------------------------------------------------------
// Listas de referencia (Presentaciones Liborio, Empleados activos) — empleados = UNIÓN de Odoo liborio (hr_employee activos) + planilla SAPPRO (ingresos sin egreso, CIA 1) — 2026-08-24. Ninguna fuente sola está completa.
// ---------------------------------------------------------------------------
const PRESENTACIONES_LIBORIO = [
  "Banda",
  "INTERGLO 80%",
  "INTERGLO 90%",
  "INTERGLO 95%",
  "QUEBRADO",
  "DP 95% 23 KG",
  "LB 99% 46 KG",
  "LB 99% 1.8 KG",
  "LB 99% 4 KG",
  "LB 99% 1 KG",
  "LB 99% 23 KG",
  "LB 99% 6 Kg",
  "LB 95% 2 kg",
  "LB 95% 6 KG",
  "LB 95% 46 KG",
  "LB 90% 2 KG",
  "LB 80% 1,8 KG",
  "LB 80% 2 KG",
  "LB 80% 10 KG",
  "LB 80% 23 KG",
  "LB 80% 46 KG",
  "LB 95% 1.8 KG",
  "LB 95% 23 KG",
  "LB 90% 46 KG",
  "LB 90% 23 KG",
  "LB 90% 5 KG",
  "CNP 95% 2  KG",
  "DP 91% 1.8 KG",
  "LB 90% 1.8 KG",
  "LB 90% 8 KG",
  "DP 80% 1.8 KG",
  "DP 80% 10 KG",
  "DP 80% 46 KG",
  "DP 90% 1.8 KG",
  "DP 95% 1.8 KG",
  "DP 95% 7 KG",
  "DP 95% 5 KG",
  "DP 95% 46 KG",
  "DP 90% 8 KG",
  "DP 99% 1.8 KG",
  "DP 99% 4 KG",
  "DP 98% 46 KG",
  "DP 90% 46 KG",
  "DP 90% 1.5 KG",
  "CAÑERO 80% 1.8 KG",
  "DP 99% 7 KG",
  "CAÑERO 90% 1.5 KG",
  "LB FIT 99% 1,8 KG",
  "LB FIT 99% 1 KG",
  "VILMA 90% 1.8 KG",
  "VILMA 99% 1.8 KG",
  "VILMA 80% 1.8 KG",
  "EL ANGEL 80% 1.8KG",
  "ANGEL 90% 1.8 KG",
  "ANGEL 99% 1.8 KG",
  "MTL 80% 1.8 KG",
  "MTL 91% 1.8 KG",
  "MTL 99% 1.8 KG",
  "ML 95% 1.8 KG",
  "ML 95% 5 KG",
  "ML 95% 3 KG",
  "CKP 80% 1.8 KG",
  "CKP 90% 1.8 KG",
  "CKP 99% 1.8 KG",
  "BM 90% 1.8 KG",
  "BM 95% 1.8 KG",
  "BM 99% 1.8 KG",
  "LB 80% 1KG",
  "DP 99% 1.5 KG",
  "BM 99% 3.8 KG",
  "CAÑERO 90% 5 KG",
  "CAÑERO 99% 1.5 KG",
];

const EMPLEADOS_ACTIVOS = [
  "ADEMAR JESUS JARQUIN BARAHONA",
  "ALAN ESGARDO MAMUD RENGIFO",
  "ALEXANDER RODRIGUEZ ROQUE",
  "ALVARO ROJAS SALGUERO",
  "AMILCAR ANTONIO MARCHENA GODINEZ",
  "ANDREA LIZETH ORTEGA BRICEÑO",
  "ANDRES HERRERA LOPEZ",
  "ANDREY GERARDO ORDOÑEZ PICADO",
  "ARELIS ISABEL MELENDEZ SANCHO",
  "AXEL ISAAC SEGURA ANCHIA",
  "Brian Jesus Villagra Sequeira",
  "BRYAN JOSUE VARELA LOPEZ",
  "CARLOS ARNOLDO MURILLO GALERA",
  "CARLOS MAURICIO ORDOÑEZ HIDALGO",
  "CESAR DIAZ ZAMORA",
  "DUVAN ESPINOZA HERNÁNDEZ",
  "EVELYN VANESSA ORDOÑEZ SALAZAR",
  "EVISAY ALBERTO SOLIS AGUIRRE",
  "FABIAN ANDREY OCONITRILLO VILCHEZ",
  "FABIAN JOSUE LOPEZ JIRON",
  "FLORICEL LARA BARRANTES",
  "FREDDY DE JESUS RUIZ MATA",
  "FREDDY QUESADA GUZMAN",
  "Giancarlo Rodriguez",
  "GUSTAVO ADOLFO GARCÍA ALVARADO",
  "JIMENA GÓMEZ VILLALOBOS",
  "JOAN MOLINA ROJAS",
  "JORGE ALBERTO MORA BARRANTES",
  "JORGE ANDRÉS REYES AGUILAR",
  "JOSE NOEL OBANDO ESPINOZA",
  "JOSÉ CIRILO PÉREZ ESPINOZA",
  "JOSUE RAMON BONILLA CASTELLON",
  "JOSUÉ ALEXANDER ARGUEDAS DÍAZ",
  "JUAN ANTONIO ULLOA PEREZ",
  "JULIO CESAR BERMUDEZ HERNANDEZ",
  "KAROLAYN ORTEGA MORA",
  "KATHIA CUBERO MARIN",
  "KENNETH ELIECER MORA MONGE",
  "KEYLING RIOS SILVA",
  "LESLIE GUEVARA HERNÁNDEZ",
  "LUIS CARLOS VARELA SIRIAS",
  "LUIS DIEGO MORALES GONZALEZ",
  "LUIS FERNANDO CHAVARRIA SANCHEZ",
  "LUIS JOSUE RODRÍGUEZ PALAVICINI",
  "LUIS RONALD SOTO GONZALEZ",
  "MAURICIO JOSUE CAMPOS PORRAS",
  "MEILYN PATRICIA OBANDO CORTES",
  "MINOR DAVID MESEN ESPINOZA",
  "NATALIA MADRIGAL BARQUERO",
  "Nathaly Mendiola Salas",
  "NELSON ANTONIO BRENES ABARCA",
  "OLMAN JESUS BARBOZA ESPINOZA",
  "ORLANDO MARIN MARIN",
  "OSVALDO BARRIOS GUTIÉRREZ",
  "PEDRO JOSUÉ ESPINOZA DUARTE",
  "RAUL ALBERTO LOPEZ REYES",
  "RONALD ANDRÉS DELGADO MARTÍNEZ",
  "SANTOS DE JESUS DUARTES HERNANDEZ",
  "SANTOS GONZÁLEZ ALVARADO",
  "SHARON MASSIEL GOMEZ SALAZAR",
  "VLADIMIR CASTRO BERMUDEZ",
  "YAHAIRA ISABEL ESPINOZA LOPEZ",
];
