// ---------------------------------------------------------------------------
// Datos maestros tomados de las hojas DATOS / Hoja2 de los libros originales
// ---------------------------------------------------------------------------
const RESPONSABLES = [
  "Diego Morales",
  "José Perez",
  "Vladimir Castro",
  "Evelyn Ordoñez",
  "Minor Mesén"
];

const AREAS_BPM = ["Empaque", "Pilado", "Frijoles", "Secado"];
const AREAS_DAC = ["Empaque", "Pilado", "Frijoles", "Secado", "Laboratorio"];
const AREAS_EPP = ["Pilado", "Secado", "Mantenimiento", "Frijoles", "Empaque"];

const DIAS_SEMANA = [
  { key: "L", label: "Lunes" },
  { key: "M", label: "Martes" },
  { key: "K", label: "Miércoles" },
  { key: "J", label: "Jueves" },
  { key: "V", label: "Viernes" },
  { key: "S", label: "Sábado" }
];

// Productos / presentaciones del R-PLP-001 (hoja DATOS)
const PRODUCTOS = [
  { codigo: "1",   nombre: "Banda",                 calidad: "N/A" },
  { codigo: "2",   nombre: "INTERGLO 80%",          calidad: "80%" },
  { codigo: "3",   nombre: "INTERGLO 90%",          calidad: "90%" },
  { codigo: "4",   nombre: "INTERGLO 95%",          calidad: "95%" },
  { codigo: "5",   nombre: "QUEBRADO",              calidad: "N/A" },
  { codigo: "23",  nombre: "DP 95% 23 KG",          calidad: "95%" },
  { codigo: "70",  nombre: "LB 99% 46 KG",          calidad: "99%" },
  { codigo: "71",  nombre: "LB 99% 1.8 KG",         calidad: "99%" },
  { codigo: "72",  nombre: "LB 99% 1.8 KG",         calidad: "99%" },
  { codigo: "73",  nombre: "LB 99% 4 KG",           calidad: "99%" },
  { codigo: "76",  nombre: "LB 99% 1 KG",           calidad: "99%" },
  { codigo: "77",  nombre: "LB 99% 23 KG",          calidad: "99%" },
  { codigo: "78",  nombre: "LB 99% 6 KG",           calidad: "99%" },
  { codigo: "101", nombre: "LB 95% 2 KG",           calidad: "95%" },
  { codigo: "102", nombre: "LB 95% 6 KG",           calidad: "95%" },
  { codigo: "103", nombre: "LB 95% 46 KG",          calidad: "95%" },
  { codigo: "104", nombre: "LB 90% 2 KG",           calidad: "90%" },
  { codigo: "106", nombre: "LB 80% 1.8 KG",         calidad: "80%" },
  { codigo: "107", nombre: "LB 80% 2 KG",           calidad: "80%" },
  { codigo: "109", nombre: "LB 80% 10 KG",          calidad: "80%" },
  { codigo: "110", nombre: "LB 80% 23 KG",          calidad: "80%" },
  { codigo: "111", nombre: "LB 80% 46 KG",          calidad: "80%" },
  { codigo: "114", nombre: "LB 95% 1.8 KG",         calidad: "95%" },
  { codigo: "118", nombre: "LB 95% 23 KG",          calidad: "95%" },
  { codigo: "122", nombre: "LB 90% 46 KG",          calidad: "90%" },
  { codigo: "125", nombre: "LB 90% 23 KG",          calidad: "90%" },
  { codigo: "130", nombre: "LB 90% 5 KG",           calidad: "90%" },
  { codigo: "134", nombre: "CNP 95% 2 KG",          calidad: "95%" },
  { codigo: "150", nombre: "DP 91% 1.8 KG",         calidad: "91%" },
  { codigo: "154", nombre: "LB 90% 1.8 KG",         calidad: "90%" },
  { codigo: "156", nombre: "LB 90% 8 KG",           calidad: "90%" },
  { codigo: "175", nombre: "DP 80% 1.8 KG",         calidad: "80%" },
  { codigo: "176", nombre: "DP 80% 10 KG",          calidad: "80%" },
  { codigo: "180", nombre: "DP 80% 46 KG",          calidad: "80%" },
  { codigo: "183", nombre: "DP 90% 1.8 KG",         calidad: "90%" },
  { codigo: "184", nombre: "DP 95% 1.8 KG",         calidad: "95%" },
  { codigo: "186", nombre: "DP 95% 7 KG",           calidad: "95%" },
  { codigo: "192", nombre: "DP 95% 5 KG",           calidad: "95%" },
  { codigo: "199", nombre: "DP 95% 46 KG",          calidad: "95%" },
  { codigo: "200", nombre: "DP 90% 8 KG",           calidad: "90%" },
  { codigo: "202", nombre: "DP 99% 1.8 KG",         calidad: "99%" },
  { codigo: "205", nombre: "DP 99% 4 KG",           calidad: "99%" },
  { codigo: "207", nombre: "DP 98% 46 KG",          calidad: "98%" },
  { codigo: "208", nombre: "DP 90% 46 KG",          calidad: "90%" },
  { codigo: "209", nombre: "DP 90% 1.5 KG",         calidad: "90%" },
  { codigo: "211", nombre: "CAÑERO 80% 1.8 KG",     calidad: "80%" },
  { codigo: "216", nombre: "DP 99% 7 KG",           calidad: "99%" },
  { codigo: "218", nombre: "CAÑERO 90% 1.5 KG",     calidad: "90%" },
  { codigo: "220", nombre: "CAÑERO 90% 5 KG",       calidad: "90%" },
  { codigo: "407", nombre: "LB FIT 99% 1.8 KG",     calidad: "99%" },
  { codigo: "411", nombre: "LB FIT 99% 1 KG",       calidad: "99%" },
  { codigo: "412", nombre: "LB FIT 99% 1.8 KG",     calidad: "99%" },
  { codigo: "511", nombre: "VILMA 90% 1.8 KG",      calidad: "90%" },
  { codigo: "512", nombre: "VILMA 99% 1.8 KG",      calidad: "99%" },
  { codigo: "513", nombre: "VILMA 80% 1.8 KG",      calidad: "80%" },
  { codigo: "515", nombre: "ANGEL 90% 1.8 KG",      calidad: "90%" },
  { codigo: "517", nombre: "ANGEL 99% 1.8 KG",      calidad: "99%" },
  { codigo: "518", nombre: "MTL 80% 1.8 KG",        calidad: "80%" },
  { codigo: "519", nombre: "MTL 91% 1.8 KG",        calidad: "91%" },
  { codigo: "520", nombre: "MTL 99% 1.8 KG",        calidad: "99%" },
  { codigo: "529", nombre: "ML 95% 1.8 KG",         calidad: "95%" },
  { codigo: "530", nombre: "ML 95% 5 KG",           calidad: "95%" },
  { codigo: "531", nombre: "ML 95% 3 KG",           calidad: "95%" },
  { codigo: "532", nombre: "CKP 80% 1.8 KG",        calidad: "80%" },
  { codigo: "534", nombre: "CKP 90% 1.8 KG",        calidad: "90%" },
  { codigo: "535", nombre: "CKP 99% 1.8 KG",        calidad: "99%" },
  { codigo: "536", nombre: "BM 90% 1.8 KG",         calidad: "90%" },
  { codigo: "537", nombre: "BM 95% 1.8 KG",         calidad: "95%" },
  { codigo: "538", nombre: "BM 99% 1.8 KG",         calidad: "99%" },
  { codigo: "539", nombre: "BM 99% 3.8 KG",         calidad: "99%" },
  { codigo: "",    nombre: "ANGEL 80% 1.8 KG",      calidad: "80%" },
  { codigo: "",    nombre: "DP 99% 1.5 KG",         calidad: "99%" }
];

// Mapa código de producto → calidad (número), derivado del catálogo de
// productos. Ej. 71 → 99. Se usa para autocompletar la calidad en el ETP.
const CODIGO_CALIDAD = {};
PRODUCTOS.forEach(function (p) {
  const m = String(p.calidad || "").match(/(\d+)\s*%/);
  if (p.codigo && m) CODIGO_CALIDAD[String(p.codigo).trim()] = m[1];
});
// Lista de códigos disponibles (para el selector del ETP).
const CODIGOS_PRODUCTO = Object.keys(CODIGO_CALIDAD);

// Los usuarios iniciales se crean en el backend (server/db.js) a partir de las
// variables de entorno SEED_ADMIN_PASSWORD y SEED_OPERATOR_PASSWORD la primera
// vez que arranca el servicio. El frontend ya no conoce credenciales.

// ---------------------------------------------------------------------------
// Listas de referencia (Presentaciones Liborio, Empleados activos) — empleados refrescados desde SAPPRO (RHVMEMPLEADO activos CIA 1) 2026-08-24.
// ---------------------------------------------------------------------------
const PRESENTACIONES_LIBORIO = [
  "Banda",
  "INTERGLO 80%",
  "INTERGLO 90%",
  "INTERGLO 95%",
  "QUEBRADO",
  "DP 95% 23 KG",
  "LB 99% 46 KG",
  "LB 99% 1.8 KG",
  "LB 99% 4 KG",
  "LB 99% 1 KG",
  "LB 99% 23 KG",
  "LB 99% 6 Kg",
  "LB 95% 2 kg",
  "LB 95% 6 KG",
  "LB 95% 46 KG",
  "LB 90% 2 KG",
  "LB 80% 1,8 KG",
  "LB 80% 2 KG",
  "LB 80% 10 KG",
  "LB 80% 23 KG",
  "LB 80% 46 KG",
  "LB 95% 1.8 KG",
  "LB 95% 23 KG",
  "LB 90% 46 KG",
  "LB 90% 23 KG",
  "LB 90% 5 KG",
  "CNP 95% 2  KG",
  "DP 91% 1.8 KG",
  "LB 90% 1.8 KG",
  "LB 90% 8 KG",
  "DP 80% 1.8 KG",
  "DP 80% 10 KG",
  "DP 80% 46 KG",
  "DP 90% 1.8 KG",
  "DP 95% 1.8 KG",
  "DP 95% 7 KG",
  "DP 95% 5 KG",
  "DP 95% 46 KG",
  "DP 90% 8 KG",
  "DP 99% 1.8 KG",
  "DP 99% 4 KG",
  "DP 98% 46 KG",
  "DP 90% 46 KG",
  "DP 90% 1.5 KG",
  "CAÑERO 80% 1.8 KG",
  "DP 99% 7 KG",
  "CAÑERO 90% 1.5 KG",
  "LB FIT 99% 1,8 KG",
  "LB FIT 99% 1 KG",
  "VILMA 90% 1.8 KG",
  "VILMA 99% 1.8 KG",
  "VILMA 80% 1.8 KG",
  "EL ANGEL 80% 1.8KG",
  "ANGEL 90% 1.8 KG",
  "ANGEL 99% 1.8 KG",
  "MTL 80% 1.8 KG",
  "MTL 91% 1.8 KG",
  "MTL 99% 1.8 KG",
  "ML 95% 1.8 KG",
  "ML 95% 5 KG",
  "ML 95% 3 KG",
  "CKP 80% 1.8 KG",
  "CKP 90% 1.8 KG",
  "CKP 99% 1.8 KG",
  "BM 90% 1.8 KG",
  "BM 95% 1.8 KG",
  "BM 99% 1.8 KG",
  "LB 80% 1KG",
  "DP 99% 1.5 KG",
  "BM 99% 3.8 KG",
  "CAÑERO 90% 5 KG",
  "CAÑERO 99% 1.5 KG",
];

const EMPLEADOS_ACTIVOS = [
  "BARBOZA ESPINOZA OLMAN JESUS",
  "BERMUDEZ HERNANDEZ JULIO CESAR",
  "BONILLA CASTELLON JOSUE RAMON",
  "CAMPOS PORRAS MAURICIO JOSUE",
  "CASTRO BERMUDEZ VLADIMIR",
  "CHAVARRIA SANCHEZ LUIS FERNANDO",
  "CUBERO MARIN KATHIA",
  "DIAZ ZAMORA CESAR",
  "DUARTES HERNANDEZ SANTOS DE JESUS",
  "ESPINOZA DUARTE PEDRO JOSUÉ",
  "ESPINOZA LOPEZ YAHAIRA ISABEL",
  "GÓMEZ VILLALOBOS JIMENA",
  "HERRERA LOPEZ ANDRES",
  "JARQUIN BARAHONA ADEMAR JESUS",
  "LARA BARRANTES FLORICEL",
  "LOPEZ JIRON FABIAN JOSUE",
  "LOPEZ REYES RAUL ALBERTO",
  "MADRIGAL BARQUERO NATALIA",
  "MAMUD RENGIFO ALAN ESGARDO",
  "MARCHENA GODINEZ AMILCAR ANTONIO",
  "MARIN MARIN ORLANDO",
  "MELENDEZ SANCHO ARELIS ISABEL",
  "Mendiola Salas Nathaly",
  "MESEN ESPINOZA MINOR DAVID",
  "MOLINA ROJAS JOAN",
  "MORA BARRANTES JORGE ALBERTO",
  "MORA MONGE KENNETH ELIECER",
  "MORALES GONZALEZ LUIS DIEGO",
  "OBANDO CORTES MEILYN PATRICIA",
  "OBANDO ESPINOZA JOSE NOEL",
  "ORDOÑEZ HIDALGO CARLOS MAURICIO",
  "ORDOÑEZ PICADO ANDREY GERARDO",
  "ORDOÑEZ SALAZAR EVELYN VANESSA",
  "ORTEGA BRICEÑO ANDREA LIZETH",
  "ORTEGA MORA KAROLAYN",
  "PÉREZ ESPINOZA JOSÉ CIRILO",
  "QUESADA GUZMAN FREDDY",
  "REYES AGUILAR JORGE ANDRÉS",
  "RIOS SILVA KEYLING",
  "RODRIGUEZ ROQUE ALEXANDER",
  "RODRÍGUEZ PALAVICINI LUIS JOSUE",
  "ROJAS SALGUERO ALVARO",
  "RUIZ MATA FREDDY DE JESUS",
  "SEGURA ANCHIA AXEL ISAAC",
  "SOLIS AGUIRRE EVISAY ALBERTO",
  "SOTO GONZALEZ LUIS RONALD",
  "ULLOA PEREZ JUAN ANTONIO",
  "VARELA LOPEZ BRYAN JOSUE",
  "VARELA SIRIAS LUIS CARLOS",
  "Villagra Sequeira Brian Jesus",
];
